config/routes.rb
Rails.application.routes.draw do
  get "/chatroom", to: "chatrooms#show"
  get "/sub_email", to: "pages#sub_email"
  get "/sub_internet", to: "pages#sub_internet"
  get "/solution", to: "solutions#index"
  get "/tickets/:id", to: "tickets#show", as: "ticket"
  get "/dashboard", to: "bookings#dashboard"
  post "/tickets", to: "tickets#create", as: "test"
  devise_for :users
  root to: "pages#home"
  resources :issues do
    #resources :tickets, except: :create
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :trainings do
    resources :bookings
  end
  resources :chatrooms, only: :show do
    resources :messages, only: :create
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :training, dependent: :destroy
  belongs_to :user
end

app/models/chatroom.rb
class Chatroom < ApplicationRecord
  has_many :messages
end

app/models/issue.rb
class Issue < ApplicationRecord
  belongs_to :ticket, optional: true
  belongs_to :user
  belongs_to :solution

  CATEGORIES = ["Problème matériel", "Problème sur internet", "Problème e-mail"]
  SUBCATEGORIES = ["Je n'arrive pas à me connecter", "Je n'arrive à envoyer un e-mail", "Je ne reçois plus mes e-mails", "Problème avec une pièce jointe", "Je reçois beaucoup de SPAMS", "Je n'arrive pas à supprimer un e-mail"]
  SUBSUBCATEGORIES = ["Je n'arrive pas à mettre une pièce jointe dans mon e-mail", "Ma pièce jointe ne s'envoie pas", "Erreur : La taille de la pièce jointe dépasse la limite maximale", "Je n'arrive à pas télécharger une pièce jointe d'un e-mail reçu"]
  validates :subsubcategory, presence: true, inclusion: { in: SUBSUBCATEGORIES}

end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :chatroom
  belongs_to :user
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :ticket, dependent: :destroy
end

app/models/solution.rb
class Solution < ApplicationRecord
end

app/models/ticket.rb
class Ticket < ApplicationRecord
  belongs_to :user
end

app/models/training.rb
class Training < ApplicationRecord
  after_validation :geocode, if: :will_save_change_to_address?
  geocoded_by :address
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :issues
  has_many :tickets
  has_many :bookings

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController

      def new
        @training = Training.find(params[:training_id])
        @booking = Booking.new
      end

      def create
        @booking = Booking.new(booking_params)
        @training = Training.find(params[:training_id])
        @booking.user = current_user
        @booking.training = @training
        if @booking.save
          flash[:notice] = "Votre réservation est un succès"
          redirect_to trainings_path
        else
          render :new
        end
      end

      def destroy
        @booking = Booking.find(params[:booking_params])
        @booking.destroy
        authorize @booking
        flash[:success] = "Votre réservation a été supprimée"
        redirect_to bookings_url
      end

      def validate
        authorize @booking
      end

      def show
        @booking = Booking.find(params[:booking_params])
        authorize @booking
      end

      def index
        skip_policy_scope
        @bookings = Booking.all
        authorize @bookings
      end

      def update
        @booking = Booking.edit(params[:booking_params])
        authorize @booking
      end

      def dashboard
        @user = current_user
        @bookings = Booking.where(user: @user)
      end

      def approve
        @booking = Booking.find_by_id(params[:id])
         @booking.update(state: "approuvé")
         if @booking.state == "approuvé"
           flash[:success] = "Réservation approuvée"
           redirect_to bookings_path
         else
           flash[:error] = "Réservation non-approuvée"
           redirect_to bookings_path
         end
      end

      private

      def booking_params
        params.require(:booking).permit(:start_date, :end_date, :training_id, :user_id)
      end

end

app/controllers/chatrooms_controller.rb
class ChatroomsController < ApplicationController
  def show
    @chatroom = Chatroom.find(params[:chatroom_params])
    @message = Message.new
  end

  private

  def chatroom_params
    params.require(:chatroom).permit(:email, :nickname, :password)
  end
end

app/controllers/issues_controller.rb
require 'rest-client'
class IssuesController < ApplicationController
  def index
    @issues = Issue.all
  end

  def show
    @issue = Issue.find(params[:id])
    @solution = @issue.solution
    
  end

  def new
   @issue = Issue.new
  end

  def create
    @issue = Issue.new(issue_params)
    @issue.user = current_user
    @issue.solution = Solution.find_by(problems: @issue.subsubcategory)
    @issue.save
    redirect_to issue_path(@issue)
  end

  private

  def issue_params
    params.require(:issue).permit(:subsubcategory)
  end

end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def create
    @chatroom = Chatroom.find(params[:chatroom_id])
    @message = Message.new(message_params)
    @message.chatroom = @chatroom
    @message.user = current_user
    if @message.save
      redirect_to chatroom_path(@chatroom)
    else
      render "chatrooms/show", status: :unprocessable_entity
    end
    
  end

  private

  def message_params
    params.require(:message).permit(:content)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home
  end

  def sub_email
  end

  def sub_internet
  end

end

app/controllers/solutions_controller.rb
class SolutionsController < ApplicationController

end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController

  def index
    @tickets = Ticket.all
  end

  def new
    @issue = Issue.find(params[:ticket_id, :solution, :status, :user_id])
    @ticket.user = current_user
    @ticket.save
  end

  def create
    @ticket = Ticket.new
    @helper = User.where(helper: true, helper_status: true).sample
    @ticket.user = current_user
    # @ticket.helper = @helper
    @ticket.save
    redirect_to ticket_path(@ticket)
  end

  def show
    @ticket = Ticket.find(params[:id])
    @ticket.user = current_user
    url = "https://api.whereby.dev/v1/meetings"
    header = {"Authorization": "Bearer #{ENV['WHEREBY_API_KEY']}", "Content-Type": "application/json"}
    body = {"endDate": "#{Time.now + 1.day}"}
    RestClient.post(url, body, header) { |response, request, result|
    JSON.parse(response.body)
    }


    #liste des helpers qui va générer update (voir cours ce matin)
  end

  def update
  end

private

  def ticket_params
    params.require(:ticket).permit(:user_id)
  end

end

app/controllers/trainings_controller.rb
class TrainingsController < ApplicationController
  def index
    @user = current_user
    @trainings = Training.all
    @markers = @trainings.geocoded.map do |training|
      {
        lat: training.latitude,
        lng: training.longitude
      }
    end
  end

  def show
    @training = Training.find(params[:id])
    @booking = Booking.new
    @markers = [{
      lat: @training.latitude,
      lng: @training.longitude}]
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/meta_tags_helper.rb
# app/helpers/meta_tags_helper.rb

module MetaTagsHelper
  def meta_title
    content_for?(:meta_title) ? content_for(:meta_title) : DEFAULT_META["meta_title"]
  end

  def meta_description
    content_for?(:meta_description) ? content_for(:meta_description) : DEFAULT_META["meta_description"]
  end

  def meta_image
    meta_image = (content_for?(:meta_image) ? content_for(:meta_image) : DEFAULT_META["meta_image"])
    # little twist to make it work equally with an asset or a url
    meta_image.starts_with?("http") ? meta_image : image_url(meta_image)
  end
end

app/views/layouts/_card-home.html.erb
<div class="row">
  <div class="card-problem onload" data-controller="scrollelement">
    <div class="pbcard">
      <!-- <%= link_to sub_email_path do %> -->
      <div class="fr-tile fr-enlarge-link fr-tile--horizontal-md">
        <div class="fr-tile__body">
            <h5>Problème matériel</h5>
            <h6>Lenteur, virus, dysfonctionnement, comportement anormal, imprimante en panne...</h6>
        </div>
        <div class="fr-tile__img">
            <span class="icn fr-icon-computer-fill" aria-hidden="true"></span>
        </div>
      </div>
     <!--  <% end %> -->
    </div>
    <div class="pbcard">
     <!-- <%= link_to sub_email_path do %> -->
      <div class="fr-tile fr-enlarge-link fr-tile--horizontal-md">
        <div class="fr-tile__body">
            <h5>Problème sur Internet</h5>
            <h6>Problème d'accès à Internet, victime d'une arnaque en ligne, problème de sécurité...</h6>
        </div>
        <div class="fr-tile__img">
            <span class="icn fr-icon-wifi-fill" aria-hidden="true"></span>
        </div>
      </div>
     <!-- <% end %> -->
    </div>
    <div class="pbcard">
      <%= link_to sub_email_path do %>
      <div class="fr-tile fr-enlarge-link fr-tile--horizontal-md">
        <div class="fr-tile__body">
            <h5>Problème e-mail</h5>
            <h6>Erreur d'envoi ou de réception, SPAM, pièce jointe trop lourde...</h6>
        </div>
        <div class="fr-tile__img">
            <span class="icn fr-icon-mail-open-fill" aria-hidden="true"></span>
        </div>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/_card-issue.html.erb
<div class="row" data-controller="simpleformcards" data-action="simpleformcards#formcard">
  <%= simple_form_for @issue do |f| %>
    <%= f.input :subsubcategory, collection: Issue::SUBSUBCATEGORIES, as: :radio_buttons %>
  <% end %>
</div>

app/views/layouts/_card-sub-email.html.erb
<div class="row">
  <div class="card-problem">
    <div class="pbcard">
     <!-- <%= link_to new_issue_path do %> -->
      <div class="fr-tile fr-enlarge-link fr-tile--horizontal-md">
        <div class="fr-tile__body">
            <h5>Je n’arrive pas à me connecter</h5>
            <h6>Vous voyez un message d'erreur vous empêchant de vous connecter</h6>
        </div>
        <div class="fr-tile__img">
            <span class="icn fr-icon-account-circle-fill" aria-hidden="true"></span>
        </div>
      </div>
     <!-- <% end %> -->
    </div>
    <div class="pbcard">
     <!-- <%= link_to new_issue_path do %> -->
      <div class="fr-tile fr-enlarge-link fr-tile--horizontal-md">
        <div class="fr-tile__body">
            <h5>Je n'arrive pas à envoyer un e-mail</h5>
            <h6>Vous avez un message d'erreur qui empêche l'envoi d'un email</h6>
        </div>
        <div class="fr-tile__img">
            <span class="icn fr-icon-wifi-fill" aria-hidden="true"></span>
        </div>
      </div>
     <!-- <% end %> -->
    </div>
    <div class="pbcard">
      <!-- <%= link_to new_issue_path do %> -->
      <div class="fr-tile fr-enlarge-link fr-tile--horizontal-md">
        <div class="fr-tile__body">
            <h5>Je ne reçois plus mes e-mails</h5>
            <h6>Vous devez recevoir un nouvel email qui ne s'affiche pas dans votre boîte mail</h6>
        </div>
        <div class="fr-tile__img">
            <span class="icn fr-icon-chat-delete-fill" aria-hidden="true"></span>
        </div>
      </div>
      <!-- <% end %> -->
    </div>
    <div class="pbcard">
      <%= link_to new_issue_path do %>
      <div class="fr-tile fr-enlarge-link fr-tile--horizontal-md">
        <div class="fr-tile__body">
            <h5>Problème avec ma pièce jointe</h5>
            <h6>Vous avez un message d'erreur empêchant l'envoi de votre pièce jointe</h6>
        </div>
        <div class="fr-tile__img">
            <span class="icn fr-icon-attachment-fill" aria-hidden="true"></span>
        </div>
      </div>
      <% end %>
    </div>
    <div class="pbcard">
      <!-- <%= link_to new_issue_path do %> -->
      <div class="fr-tile fr-enlarge-link fr-tile--horizontal-md">
        <div class="fr-tile__body">
            <h5>Je reçois beaucoup de SPAMS</h5>
            <h6>Vous recevez des mails intempestifs de destinaire inconnu</h6>
        </div>
        <div class="fr-tile__img">
            <span class="icn fr-icon-error-fill" aria-hidden="true"></span>
        </div>
      </div>
      <!-- <% end %> -->
    </div>
    <div class="pbcard">
      <!-- <%= link_to new_issue_path do %> -->
      <div class="fr-tile fr-enlarge-link fr-tile--horizontal-md">
        <div class="fr-tile__body">
            <h5>Je n’arrive pas à supprimer un e-mail</h5>
            <h6>Vous n'arrivez pas à faire un tri dans votre boîte mail</h6>
        </div>
        <div class="fr-tile__img">
            <span class="icn fr-icon-delete-fill" aria-hidden="true"></span>
        </div>
      </div>
     <!-- <% end %> -->
    </div>
  </div>
</div>

app/views/layouts/_card-training.html.erb
<div class="card-training">
  <% @trainings.each do |training| %>
  <div class="pbcard">


    <div class="fr-card">
    <div class="fr-card__body">
        <div class="fr-card__content">
            <h3 class="fr-card__title">
               <%= link_to training.title, training_path(training) %>
            </h3>
            <h6 class="text-secondary">Catégorie : <%= training.category %></h6>
            <p class="fr-card__desc"><%= training.description %></p>
        </div>
        <div class="fr-card__footer">
            <ul class="fr-btns-group fr-btns-group--inline-reverse fr-btns-group--inline-lg">
                <li>
                    <%= link_to training do %>
                      <button class="fr-btn">Inscription</button>
                    <% end %>
                </li>
            </ul>
        </div>
    </div>
    <div class="fr-card__header">
        <div class="fr-card__img">
          <%= image_tag training.image, alt:"image débutant" %>
        </div>
    </div>
</div>


  </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
  <%= favicon_link_tag %>
  <link href="https://api.mapbox.com/mapbox-gl-js/v2.11.0/mapbox-gl.css" rel="stylesheet">
  <script src="https://api.mapbox.com/mapbox-gl-js/v2.11.0/mapbox-gl.js"></script>
    <title><%= meta_title %></title>
    <meta name="description" content="<%= meta_description %>">

    <!-- Facebook Open Graph data -->
    <meta property="og:title" content="<%= meta_title %>" />
    <meta property="og:type" content="website" />
    <meta property="og:url" content="<%= request.original_url %>" />
    <meta property="og:image" content="<%= meta_image %>" />
    <meta property="og:description" content="<%= meta_description %>" />
    <meta property="og:site_name" content="<%= meta_title %>" />

    <!-- Twitter Card data -->
    <meta name="twitter:card" content="summary_large_image">
    <meta name="twitter:site" content="<%= DEFAULT_META["twitter_account"] %>">
    <meta name="twitter:title" content="<%= meta_title %>">
    <meta name="twitter:description" content="<%= meta_description %>">
    <meta name="twitter:creator" content="<%= DEFAULT_META["twitter_account"] %>">
    <meta name="twitter:image:src" content="<%= meta_image %>">

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="theme-color" content="#000091"><!-- Défini la couleur de thème du navigateur (Safari/Android) -->

    <!-- obligé de charger le css du gouvernement car que des problèmes -->
    <link href="https://www.systeme-de-design.gouv.fr/_nuxt/css/c868e86.css" rel="stylesheet">

    <link rel="stylesheet" href="https://cdn.plyr.io/3.7.3/plyr.css" />
    <script src="https://cdn.plyr.io/3.7.3/plyr.polyfilled.js"></script>


    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
  <%= render "shared/navbar" %>
  <%= render "shared/flashes" %>

  <div class="content">
    <%= yield %>
  </div>
  </body>
</html>

app/views/pages/home.html.erb
<div class="homeimg">
  <%= image_tag "icone-debutant.png", width: "500",  alt:"image débutant" %>
</div>
<div class="main col-10">
  <div class="mb-4">
    <h1>Résolvons <strong>ensemble</strong> votre problème informatique</h1>
    <p>Vous avez un problème sur votre ordinateur ? Nous sommes là pour vous aider.</br>Si vous n'arrivez toujours pas à le résoudre, n'hésitez pas à communiquer avec l'un de nos Assistants.</p>
  </div>
  <div class="main-card">
  <!-- langage selector -->
<nav role="navigation" class="fr-translate fr-nav langnav">
    <div class="fr-nav__item flex-row-reverse">
        <button class="fr-translate__btn fr-btn fr-btn--tertiary" aria-controls="translate-1177" aria-expanded="false" title="Sélectionner une langue">
            Français<span class="fr-hidden-lg"> - Français</span>
        </button>
        <div class="fr-collapse fr-translate__menu fr-menu" id="translate-1177">
            <ul class="fr-menu__list">
                <li>
                    <a class="fr-translate__language fr-nav__link" hreflang="fr" lang="fr" href="#" aria-current="true">FR - Français</a>
                </li>
                <li>
                    <a class="fr-translate__language fr-nav__link" hreflang="en" lang="en" href="#">EN - English</a>
                </li>
                <li>
                    <a class="fr-translate__language fr-nav__link" hreflang="es" lang="es" href="#">ES - Español</a>
                </li>
                <li>
                    <a class="fr-translate__language fr-nav__link" hreflang="de" lang="de" href="#">DE - Deutsch</a>
                </li>
            </ul>
        </div>
    </div>
</nav>
<!-- -->
    <div class="card-content">
      <h2>Veuillez sélectionner votre problème</h2>
      <p>À la suite d'étapes, nous allons ensemble vous aider à le résoudre votre problème.</p>
    </div>
      <%= render "layouts/card-home" %>
  </div>


  <!--
  <div class="btn-prev">
    <button class="fr-btn fr-btn--secondary">Retour</button>
  </div>
  <div class="btn-next">
    <button class="fr-btn fr-btn--icon-right fr-icon-arrow-right-s-line">Poursuivre</button>
  </div>
  -->
</div>

<%= render "shared/footer" %>

app/views/pages/sub_email.html.erb
<%= render "shared/delete-navbar" %>

<div class="main col-10">
  <div class="main-card">
  <div class="card-content">
    <div class="fr-stepper mb-0">
      <h2 class="fr-stepper__title mb-0">
      <span class="fr-stepper__state">Étape 1 sur 3</span>
      <h1 class="title-step">Problème e-mail</h1>
      </h2>
      <div class="fr-stepper__steps" data-fr-current-step="1" data-fr-steps="3"></div>
        <p class="fr-stepper__details">
        <span class="fr-text--bold">Étape suivante :</span> Détails supplémentaires concernant votre problème
        </p>
      </div>
    </div>
    <%= render "layouts/card-sub-email" %>
  </div>

  <%= link_to :back do %>
  <div class="btn-prev">
    <button class="fr-btn fr-btn--icon-left fr-btn--secondary fr-icon-arrow-left-s-line">Retour</button>
  </div>
  <% end %>
  <!-- bouton next
  <%= link_to new_issue_path do %>
  <div class="btn-next">
    <button class="fr-btn fr-btn--icon-right fr-icon-arrow-right-s-line">Poursuivre</button>
  </div>
  <% end %>-->
</div>

<%= render "shared/footer" %>

app/views/shared/_delete-navbar.html.erb
<style>
.navbar{display:none;}
.main-card{margin-top:2em;}
</style>
<div class="main col-10">
  <div class="deletenavbar">
    <%= link_to "/" do %>
    <button class="fr-btn fr-btn--icon-left fr-btn--secondary fr-icon-home-4-line">Retour à la page d'accueil</button>
    <% end %>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>